# Generated by Django 5.2.7 on 2025-11-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=13)),
                ('full_names', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('cellphone', models.CharField(max_length=10)),
                ('confirm_cellphone', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
