# Generated by Django 5.2.7 on 2025-11-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=13, unique=True)),
                ('full_names', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=100)),
                ('cellphone', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
